<?php

return array(
    'categories_presets' => array(
        0 => array(
			"nav_bg" => "#1e73be",
			"hide_nav_bg" => "on",
			"text_bg" => "#82a0bf",
			"hide_text_bg" => "on",
			"text_color" => "#1e73be",
			"theme_color" => "off",
			"padding" => array("vert" => "3",
				"hor" => "10"),
			"font_weight" =>"normal",
			"font_size" => "12",
			"border" => array("width" => "1",
				"style" => "solid",
				"color" =>"#1e73be",
				"radius" => "3",
				"radius_unit" =>"px")
        ),
        1 => array(
			"nav_bg" => "#1e73be",
            "hide_nav_bg" => "on",
            "text_bg" => "#82a0bf",
            "hide_text_bg" => "on",
            "text_color" => "#000000",
			"theme_color" => "off",
            "padding" => array("vert" => "1",
                "hor" => "10"),
            "font_weight" =>"normal",
            "font_size" => "12",
            "border" => array("width" => "1",
                "style" => "none",
                "color" =>"#b2b2b2",
                "radius" => "3",
                "radius_unit" =>"px")
        ),
        2 => array(
			"nav_bg" => "#1e73be",
            "hide_nav_bg" => "on",
            "text_bg" => "#82a0bf",
            "hide_text_bg" => "on",
            "text_color" => "#0a0a0a",
			"theme_color" => "off",
            "padding" => array("vert" => "1",
                "hor" => "10"),
            "font_weight" =>"normal",
            "font_size" => "12",
            "border" => array("width" => "4",
                "style" => "solid",
                "color" =>"#1e73be",
                "radius" => "20",
                "radius_unit" =>"px")
        ),
        3 => array(
			"nav_bg" => "#1e73be",
            "hide_nav_bg" => "on",
            "text_bg" => "#82a0bf",
            "hide_text_bg" => "on",
            "text_color" => "#1e73be",
			"theme_color" => "off",
            "padding" => array("vert" => "3",
                "hor" => "10"),
            "font_weight" =>"normal",
            "font_size" => "12",
            "border" => array("width" => "1",
                "style" => "solid",
                "color" =>"#000000",
                "radius" => "50",
                "radius_unit" =>"px")
        ),
        4 => array(
			"nav_bg" => "#1e73be",
            "hide_nav_bg" => "on",
            "text_bg" => "#82a0bf",
            "hide_text_bg" => "on",
            "text_color" => "#dd3333",
			"theme_color" => "off",
            "padding" => array("vert" => "3",
                "hor" => "4"),
            "font_weight" =>"normal",
            "font_size" => "12",
            "border" => array("width" => "1",
                "style" => "solid",
                "color" =>"#000000",
                "radius" => "0",
                "radius_unit" =>"px")
        ),
        5 => array(
			"nav_bg" => "#1e73be",
            "hide_nav_bg" => "on",
            "text_bg" => "#82a0bf",
            "hide_text_bg" => "on",
            "text_color" => "#000000",
			"theme_color" => "off",
            "padding" => array("vert" => "6",
                "hor" => "10"),
            "font_weight" =>"normal",
            "font_size" => "12",
            "border" => array("width" => "0",
                "style" => "solid",
                "color" =>"#1e73be",
                "radius" => "40",
                "radius_unit" =>"px")
        ),
		6 => array(
			"nav_bg" => "#585858",
			"hide_nav_bg" => "on",
			"text_bg" => "#d8d8d8",
			"hide_text_bg" => "on",
			"text_color" => "#585858",
			"theme_color" => "off",
			"padding" => array("vert" => "7",
				"hor" => "10"),
			"font_weight" => "600",
			"font_size" => "12",
			"border" => array("width" => "1",
				"style" => "solid",
				"color" =>"#585858",
				"radius" => "0",
				"radius_unit" =>"px")
		),
		7 => array(
			"nav_bg" => "#0174df",
			"hide_nav_bg" => "on",
			"text_bg" => "#ff8000",
			"hide_text_bg" => "on",
			"text_color" => "#0174df",
			"theme_color" => "off",
			"padding" => array("vert" => "10",
				"hor" => "15"),
			"font_weight" => "bold",
			"font_size" => "12",
			"border" => array("width" => "2",
				"style" => "solid",
				"color" =>"#ff8000",
				"radius" => "5",
				"radius_unit" =>"px")
		),
		8 => array(
			"nav_bg" => "#2e2e2e",
			"hide_nav_bg" => "on",
			"text_bg" => "#2ecc71",
			"hide_text_bg" => "on",
			"text_color" => "#2e2e2e",
			"theme_color" => "off",
			"padding" => array("vert" => "5",
				"hor" => "10"),
			"font_weight" => "bold",
			"font_size" => "12",
			"border" => array("width" => "3",
				"style" => "solid",
				"color" =>"#2ecc71",
				"radius" => "50",
				"radius_unit" =>"px")
		),
		9 => array(
			"nav_bg" => "#dba901",
			"hide_nav_bg" => "on",
			"text_bg" => "#823aa0",
			"hide_text_bg" => "on",
			"text_color" => "#dba901",
			"theme_color" => "off",
			"padding" => array("vert" => "10",
				"hor" => "10"),
			"font_weight" => "bold",
			"font_size" => "14",
			"border" => array("width" => "2",
				"style" => "solid",
				"color" =>"#9e54bd",
				"radius" => "0",
				"radius_unit" =>"px")
		),
		10 => array(
			"nav_bg" => "#ffbf00",
			"hide_nav_bg" => "on",
			"text_bg" => "#58fa82",
			"hide_text_bg" => "on",
			"text_color" => "#ffbf00",
			"theme_color" => "off",
			"padding" => array("vert" => "10",
				"hor" => "10"),
			"font_weight" => "bold",
			"font_size" => "14",
			"border" => array("width" => "2",
				"style" => "dotted",
				"color" =>"#f4fa58",
				"radius" => "0",
				"radius_unit" =>"px")
		),
    ),
);